version: '3.8'

services:
  db:
    image: postgres:13
    environement:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: fastapi_db
    networks:
      - fastapi-net
    ports:
      -"5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - fastapi-net
    ports:
      - "8000:8000"
    environement:
      DATABASE_URL: "postgresql+asyncpg://fastapi_user:secret_password@db/fastapi_db"
    command: ["pytest", "/tests/"]
networks:
  fastapi-net:
    driver: bridge